ESTACIONAMENTO/Models/Manobra2.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ESTACIONAMENTO.Models
{
    public class Manobra2 : Base
    {
        
        [ScaffoldColumn(false)]
        public DateTime DataEntrada { get; set; }
        
        public DateTime DataSaida { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public string Classificacao { get; set; }

        public string Status { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Valor { get; set; }

        public virtual int CarroId { get; set; }
        public virtual Carro Carro { get; set; }

        public virtual int ManobristaId { get; set; }
        public virtual Manobrista Manobrista { get; set; }
    }
}

ESTACIONAMENTO/Controllers/Manobra2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ESTACIONAMENTO.Dados;
using ESTACIONAMENTO.Models;
using ESTACIONAMENTO.Extensoes;

namespace ESTACIONAMENTO.Controllers
{
    public class Manobra2Controller : Controller
    {
        private readonly EstacionamentoContext _context;

        public Manobra2Controller(EstacionamentoContext context)
        {
            _context = context;
        }

        // GET: Manobra2
        public async Task<IActionResult> IndexA()
        {
            var estacionamentoContext = await _context.Manobras2.Include(m => m.Carro)
                                                                .Include(m => m.Manobrista)
                                                                .Where(s => s.Status == "Aberta")
                                                                .ToListAsync();

            return View(estacionamentoContext);
        }

        // GET: Manobra2
        public async Task<IActionResult> IndexF()
        {
            var estacionamentoContext = await _context.Manobras2.Include(m => m.Carro)
                                                                .Include(m => m.Manobrista)
                                                                .Where(s => s.Status == "Fechada")
                                                                .ToListAsync();
            return View(estacionamentoContext);
        }

        public async Task<IActionResult> IndexR_E()
        {
            ViewData["Carros"] = new SelectList(await _context.Carros.ToListAsync(), "Id", "Modelo");
            ViewData["Manobristas"] = new SelectList(await _context.Manobristas.ToListAsync(), "Id", "Nome");
            ViewData["Classificacoes"] = new SelectList(await _context.Classificacoes.ToListAsync(), "Descricao", "Descricao");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> IndexR_E(Manobra2 man, DateTime inicio, DateTime fim)
        {
            ViewData["Carros"] = new SelectList(await _context.Carros.ToListAsync(), "Id", "Modelo");
            ViewData["Manobristas"] = new SelectList(await _context.Manobristas.ToListAsync(), "Id", "Nome");
            ViewData["Classificacoes"] = new SelectList(await _context.Classificacoes.ToListAsync(), "Descricao", "Descricao");

            fim = fim.AddHours(24);

            // Por Carro
            if (man.CarroId != 0 && man.ManobristaId == 0 && man.Classificacao == "0")
            {
                if (inicio.ToShortDateString() != "01/01/0001" && fim.ToShortDateString() != "01/01/0001")
                {
                    var manobras = await _context.Manobras2.Where(m => m.CarroId == man.CarroId && (m.DataEntrada >= inicio && m.DataEntrada <= fim)).ToListAsync();
                    return View("IndexR_E", manobras);
                }
                else
                {
                    var manobras = await _context.Manobras2.Where(m => m.CarroId == man.CarroId).ToListAsync();
                    return View("IndexR_E", manobras);
                }
            }

            // Por Manobrista
            if (man.CarroId == 0 && man.ManobristaId != 0 && man.Classificacao == "0")
            {
                if (inicio.ToShortDateString() != "01/01/0001" && fim.ToShortDateString() != "01/01/0001")
                {
                    var manobras = await _context.Manobras2.Where(m => m.ManobristaId == man.ManobristaId && (m.DataEntrada >= inicio && m.DataEntrada <= fim)).ToListAsync();
                    return View("IndexR_E", manobras);
                }
                else
                {
                    var manobras = await _context.Manobras2.Where(m => m.ManobristaId == man.ManobristaId).ToListAsync();
                    return View("IndexR_E", manobras);
                }
            }

            // Por Classificação
            if (man.CarroId == 0 && man.ManobristaId == 0 && man.Classificacao != "0")
            {
                if (inicio.ToShortDateString() != "01/01/0001" && fim.ToShortDateString() != "01/01/0001")
                {
                    var manobras = await _context.Manobras2.Where(m => m.Classificacao == man.Classificacao && (m.DataEntrada >= inicio && m.DataEntrada <= fim)).ToListAsync();
                    return View("IndexR_E", manobras);
                }
                else
                {
                    var manobras = await _context.Manobras2.Where(m => m.Classificacao == man.Classificacao).ToListAsync();
                    return View("IndexR_E", manobras);
                }
            }

            // Por Carro/Manobrista
            if (man.CarroId != 0 && man.ManobristaId != 0 && man.Classificacao == "0")
            {
                if (inicio.ToShortDateString() != "01/01/0001" && fim.ToShortDateString() != "01/01/0001")
                {
                    var manobras = await _context.Manobras2.Where(m => m.CarroId == man.CarroId &&
                                                                       m.ManobristaId == man.ManobristaId &&
                                                                      (m.DataEntrada >= inicio && m.DataEntrada <= fim)).ToListAsync();
                    return View("IndexR_E", manobras);
                }
                else
                {
                    var manobras = await _context.Manobras2.Where(m => m.CarroId == man.CarroId &&
                                                                       m.ManobristaId == man.ManobristaId).ToListAsync(); ;
                    return View("IndexR_E", manobras);
                }
            }

            // Por Carro/Classificação
            if (man.CarroId != 0 && man.ManobristaId == 0 && man.Classificacao != "0")
            {
                if (inicio.ToShortDateString() != "01/01/0001" && fim.ToShortDateString() != "01/01/0001")
                {
                    var manobras = await _context.Manobras2.Where(m => m.CarroId == man.CarroId &&
                                                                       m.Classificacao == man.Classificacao &&
                                                                      (m.DataEntrada >= inicio && m.DataEntrada <= fim)).ToListAsync();
                    return View("IndexR_E", manobras);
                }
                else
                {
                    var manobras = await _context.Manobras2.Where(m => m.CarroId == man.CarroId &&
                                                                       m.Classificacao == man.Classificacao).ToListAsync(); ;
                    return View("IndexR_E", manobras);
                }
            }

            // Por Manobrista/Classificação
            if (man.CarroId == 0 && man.ManobristaId != 0 && man.Classificacao != "0")
            {
                if (inicio.ToShortDateString() != "01/01/0001" && fim.ToShortDateString() != "01/01/0001")
                {
                    var manobras = await _context.Manobras2.Where(m => m.ManobristaId == man.ManobristaId &&
                                                                       m.Classificacao == man.Classificacao &&
                                                                      (m.DataEntrada >= inicio && m.DataEntrada <= fim)).ToListAsync();
                    return View("IndexR_E", manobras);
                }
                else
                {
                    var manobras = await _context.Manobras2.Where(m => m.ManobristaId == man.ManobristaId &&
                                                                       m.Classificacao == man.Classificacao).ToListAsync(); ;
                    return View("IndexR_E", manobras);
                }
            }

            // Por Carro/Manobrista/Classificação
            if (man.CarroId != 0 && man.ManobristaId != 0 && man.Classificacao != "0")
            {
                if (inicio.ToShortDateString() != "01/01/0001" && fim.ToShortDateString() != "01/01/0001")
                {
                    var manobras = await _context.Manobras2.Where(m => m.CarroId == man.CarroId &&
                                                                       m.ManobristaId == man.ManobristaId &&
                                                                       m.Classificacao == man.Classificacao &&
                                                                      (m.DataEntrada >= inicio && m.DataEntrada <= fim)).ToListAsync();
                    return View("IndexR_E", manobras);
                }
                else
                {
                    var manobras = await _context.Manobras2.Where(m => m.CarroId == man.CarroId &&
                                                                       m.ManobristaId == man.ManobristaId &&
                                                                       m.Classificacao == man.Classificacao).ToListAsync(); ;
                    return View("IndexR_E", manobras);
                }
            }

            return View();

        }


        // GET: Manobra2/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manobra2 = await _context.Manobras2
                .Include(m => m.Carro)
                .Include(m => m.Manobrista)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manobra2 == null)
            {
                return NotFound();
            }

            return View(manobra2);
        }

        // GET: Manobra2/Create
        public IActionResult Create()
        {
            ViewData["Mensagem"] = "";
            ViewData["Carros"] = new SelectList(_context.Carros, "Id", "Modelo");

ESTACIONAMENTO/Controllers/Manobra2RelatorioController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ESTACIONAMENTO.Dados;
using Rotativa;
using Rotativa.AspNetCore;

namespace ESTACIONAMENTO.Controllers
{
    public class Manobra2RelatorioController : Controller
    {
        private readonly EstacionamentoContext _context;

        public Manobra2RelatorioController(EstacionamentoContext context)
        {
            _context = context;
        }

        // GET: Manobra2/ReciboP/5
        public async Task<ViewAsPdf> ReciboP(int? id)
        {
            var manobra2 = await _context.Manobras2.FindAsync(id);
            var reciboPDF = new ViewAsPdf()
            {
                ViewName = "ReciboP",
                IsGrayScale = true,
                Model = manobra2
            };
            return reciboPDF;
        }

    }
}

ESTACIONAMENTO/Views/Manobra2/Create.cshtml
@model ESTACIONAMENTO.Models.Manobra2

@{
    ViewData["Title"] = "Cadastrar";
    var msg = ViewBag.Mensagem;
}

<script src="~/js/site.js"></script>
<link href="~/css/site.css" rel="stylesheet" />

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row border1">
    <div class="col-md-4">
        <div>
            <h4>Manobra - Recepção/@Model.Status</h4>
            <hr />
        </div>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Carro</label>
                <select asp-for="CarroId" class="form-control" asp-items="ViewBag.Carros"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Manobrista</label>
                <select asp-for="ManobristaId" class="form-control" asp-items="ViewBag.Manobristas"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Tipo Manobra</label>
                <select asp-for="Classificacao" id="classificacao" class="form-control" asp-items="ViewBag.Classificacoes" disabled></select>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" id="status" disabled />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" onclick="HabilitaStatus();" />
            </div>

        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="IndexA">Retorna para Lista</a>
</div>

@{
    if (msg != string.Empty)
    {
        <br />
        <div class="alert-warning">
            <p>@msg</p>
        </div>
    }
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ESTACIONAMENTO/Views/Manobra2/Delete.cshtml
@model ESTACIONAMENTO.Models.Manobra2

@{
    ViewData["Title"] = "Excluir";
}

<h1>@ViewData["Title"]</h1>

<h3>Confirma a exclusão?</h3>
<div>
    <h4>Manobra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataEntrada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataEntrada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Classificacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Classificacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carro.Modelo)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manobrista)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manobrista.Nome)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="IndexA">Retorna para Lista</a>
    </form>
</div>

ESTACIONAMENTO/Views/Manobra2/Details.cshtml
@model ESTACIONAMENTO.Models.Manobra2

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Manobra2</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataSaida)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataSaida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Classificacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Classificacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carro.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manobrista)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manobrista.CPF)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ESTACIONAMENTO/Views/Manobra2/Edit.cshtml
@model ESTACIONAMENTO.Models.Manobra2

@{
    ViewData["Title"] = "Editar";
}

<script src="~/js/site.js"></script>

<h1>@ViewData["Title"]</h1>

<div class="row border1">
    <div class="col-md-4">
        <div>
            <h4>Manobra</h4>
            <hr />
        </div>
        <form asp-action="Edit" id="editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Carro</label>
                <select asp-for="CarroId" class="form-control" asp-items="ViewBag.Carros"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Manobrista</label>
                <select asp-for="ManobristaId" class="form-control" asp-items="ViewBag.Manobristas"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Tipo Manobra</label>
                <select asp-for="Classificacao" id="Classificacao" class="form-control" asp-items="ViewBag.Classificacoes" disabled></select>
            </div>
            <div class="form-group">
                <label asp-for="DataEntrada" class="control-label"></label>
                <input asp-for="DataEntrada" id="DataEntrada" class="form-control" disabled />
                <span asp-validation-for="DataEntrada" class="text-danger"></span>
            </div>
            <div class="form-group" hidden="hidden">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" id="Status" class="form-control" disabled />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" onclick="HabilitaTodosE();" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="IndexA">Retorna para Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ESTACIONAMENTO/Views/Manobra2/Fechar.cshtml
@model ESTACIONAMENTO.Models.Manobra2

@{
    ViewData["Title"] = "Fechar";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>Manobra - @Model.Classificacao/@Model.Status</h4>
</div>
<hr />
<div class="border1">
    <div>
        <div class="col-md-4">
            <form asp-action="Fechar" id="fechar">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="DataSaida" class="control-label"></label>
                    <input asp-for="DataSaida" id="DataSaida" class="form-control" disabled />

                </div>
                <div class="form-group">
                    <label asp-for="DataEntrada" class="control-label"></label>
                    <input asp-for="DataEntrada" id="DataEntrada" class="form-control" disabled />

                </div>
                <div class="form-group">
                    <label asp-for="Classificacao" class="control-label"></label>
                    <input asp-for="Classificacao" id="Classificacao" class="form-control" disabled />

                </div>
                <div class="form-group">
                    <label asp-for="Status" class="control-label"></label>
                    <input asp-for="Status" id="Status" class="form-control" disabled />

                </div>
                <div class="form-group" hidden="hidden">
                    <label asp-for="CarroId" class="control-label"></label>
                    <input asp-for="CarroId" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="Carro.Modelo" class="control-label"></label>
                    <input asp-for="Carro.Modelo" id="CarroModelo" class="form-control" disabled />

                </div>
                <div class="form-group" hidden="hidden">
                    <label asp-for="ManobristaId" class="control-label"></label>
                    <input asp-for="ManobristaId" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="Manobrista.Nome" class="control-label"></label>
                    <input asp-for="Manobrista.Nome" id="ManobristaNome" class="form-control" disabled />

                </div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <input type="submit" value="Encerrar Serviço" class="btn btn-primary" onclick="HabilitaTodos();" />
                </div>
            </form>
        </div>
    </div>
</div>

<br />
<div>
    <a asp-action="IndexA">Retorna para Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ESTACIONAMENTO/Views/Manobra2/IndexA.cshtml
@model IEnumerable<ESTACIONAMENTO.Models.Manobra2>

@{
    ViewData["Title"] = "Manobras - Abertas";
}

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<br />
<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-2">
        <p>
            <a class="btn btn-primary" asp-action="Create">Nova</a>
            <a class="btn btn-secondary" href="https://localhost:44328/Manobra2/IndexF">Fechadas</a>
        </p>
    </div>
</div>

<table class="table table-hover">
    <thead>
        <tr style="background-color:cadetblue">
            <th>
                @Html.DisplayNameFor(model => model.Carro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Carro.Placa)
            </th>
            <th>
                Tipo Manobra
            </th>
            <th>
                Manobrista
            </th>
            <th>
                Data/Hora Entrada
            </th>
            <th>
                Data/Hora Saída
            </th>
            <th>
                Situação
            </th>

            <th>
                Ações Disponíveis
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Carro.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Carro.Placa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Classificacao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Manobrista.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataEntrada)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataSaida)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>

                <td>
                    <div class="text-right">
                        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
                        <a class="btn btn-secondary" asp-action="Fechar" asp-route-id="@item.Id">Fechar</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

ESTACIONAMENTO/Views/Manobra2/IndexF.cshtml
@model IEnumerable<ESTACIONAMENTO.Models.Manobra2>

@{
    ViewData["Title"] = "Manobras - Fechadas";
}
<br />
<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-6">
        <a class="btn btn-success" href="https://localhost:44328/Manobra2/IndexA">Abertas</a>
    </div>
    
    <div class="col-6 text-right">
        <p>Total faturado para o período: <span style="background-color:gold">[ <b>R$ @Model.Sum(v => v.Valor)</b> ]</span></p>
    </div>
</div>

<table class="table table-hover">
    <thead>
        <tr style="background-color:cadetblue">
            <th>
                @Html.DisplayNameFor(model => model.Carro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Carro.Placa)
            </th>
            <th>
                Manobrista
            </th>
            <th>
                Data/Hora Entrada
            </th>
            <th>
                Data/Hora Saída
            </th>
            <th>
                Tempo(m)
            </th>
            <th>
                Situação
            </th>
            <th>
                Valor R$
            </th>
            <th>
                Ações Disponíveis
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var tempo = (int)((item.DataSaida - item.DataEntrada).TotalMinutes);
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Carro.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Carro.Placa)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Manobrista.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataEntrada)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataSaida)
                </td>
                <td style="text-align:center">
                    @tempo
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td style="text-align:right">
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td class="text-right">
                    <a class="btn btn-dark" asp-action="Recibo" asp-route-id="@item.Id">Emitir Recibo</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ESTACIONAMENTO/Views/Manobra2/Recibo.cshtml
@model ESTACIONAMENTO.Models.Manobra2
@using ESTACIONAMENTO.Extensoes;

@{
    ViewData["Title"] = "Recibo de Pagamento";
    var tempo = (int)(Model.DataSaida - Model.DataEntrada).TotalMinutes;
}

<br />
<div>
    <div class="row" style="background-color:darkgrey;text-align:left">
        <div class="col-6">
            <h1>@ViewData["Title"]</h1>
            <h4>Manobra - @Model.Classificacao/@Model.Status</h4>
        </div>

        <div class="col-md-6 text-right" style="">
            <h5>
                Emitido em: @DateTime.Now
            </h5>
        </div>
        <hr />
    </div>

    <dl class="row" style="background-color:gainsboro">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataEntrada)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataEntrada)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataSaida)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataSaida)
        </dd>
        <dt class="col-sm-2">
            Permanência
        </dt>
        <dd class="col-sm-10">
            @tempo minutos
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Classificacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Classificacao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Carro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Carro.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Carro.Placa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Carro.Placa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Manobrista)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Manobrista.Nome)
        </dd>
        <dt class="col-sm-2">
            Valor R$
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Valor) (@Model.Valor.ToExtenso())
        </dd>
    </dl>
</div>
<hr />
<div>
    <a class="btn btn-dark" asp-action="ReciboP" asp-controller="Manobra2Relatorio" asp-route-id="@Model.Id">Imprimir</a>
    <a class="btn btn-secondary" asp-action="IndexF">Retorna para Lista</a>
</div>