ESTACIONAMENTO/Controllers/CarroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ESTACIONAMENTO.Dados;
using ESTACIONAMENTO.Models;

namespace ESTACIONAMENTO.Controllers
{
    public class CarroController : Controller
    {
        private readonly EstacionamentoContext _context;

        public CarroController(EstacionamentoContext context)
        {
            _context = context;
        }

        // GET: Carro
        public async Task<IActionResult> Index()
        {
            //var cc = await _context.Carros.ToListAsync();
            return View(await _context.Carros.ToListAsync());
        }

        // GET: Carro/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        // GET: Carro/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Carro/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Marca,Modelo,Placa,Id")] Carro carro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(carro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carro/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.FindAsync(id);
            if (carro == null)
            {
                return NotFound();
            }
            return View(carro);
        }

        // POST: Carro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Marca,Modelo,Placa,Id")] Carro carro)
        {
            if (id != carro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarroExists(carro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carro/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        // POST: Carro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carro = await _context.Carros.FindAsync(id);
            _context.Carros.Remove(carro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarroExists(int id)
        {
            return _context.Carros.Any(e => e.Id == id);
        }
    }
}

ESTACIONAMENTO/Controllers/ManobraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ESTACIONAMENTO.Dados;
using ESTACIONAMENTO.Models;

namespace ESTACIONAMENTO.Controllers
{
    public class ManobraController : Controller
    {
        private readonly EstacionamentoContext _context;
       
        public ManobraController(EstacionamentoContext context)
        {
            _context = context;
        }

        // GET: Manobra
        public async Task<IActionResult> Index()
        {
            return View(await _context.Manobras.OrderByDescending(p => p.Carro.Placa).ToListAsync());
        }

        // GET: Manobra/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manobra = await _context.Manobras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manobra == null)
            {
                return NotFound();
            }

            return View(manobra);
        }

        // GET: Manobra/Create
        public IActionResult Create()
        {
            var carros = _context.Carros.ToList();
            ViewData["Carros"] = new SelectList(carros, "Id", "Modelo");
            var manobristas = _context.Manobristas.ToList();
            ViewData["Manobristas"] = new SelectList(manobristas, "Id", "Nome");
            var classificacao = _context.Classificacoes.ToList();
            ViewData["Classificacoes"] = new SelectList(classificacao, "Descricao", "Descricao");

            return View();
        }

        // POST: Manobra/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Manobra manobra)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manobra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(manobra);
        }

        // GET: Manobra/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            

            var manobra = await _context.Manobras.FindAsync(id);
            if (manobra == null)
            {
                return NotFound();
            }

            var carros = _context.Carros.ToList();
            ViewData["Carros"] = new SelectList(carros, "Id", "Modelo", manobra.Carro.Modelo);
            var manobristas = _context.Manobristas.ToList();
            ViewData["Manobristas"] = new SelectList(manobristas, "Id", "Nome", manobra.Manobrista.Nome);
            var classificacao = _context.Classificacoes.ToList();
            ViewData["Classificacoes"] = new SelectList(classificacao, "Descricao", "Descricao", manobra.Classificacao);
            return View(manobra);
        }

        // POST: Manobra/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarroId,ManobristaId,Classificacao,TipoManobra,Id")] Manobra manobra)
        {
            if (id != manobra.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manobra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ManobraExists(manobra.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manobra);
        }

        // GET: Manobra/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manobra = await _context.Manobras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manobra == null)
            {
                return NotFound();
            }

            return View(manobra);
        }

        // POST: Manobra/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manobra = await _context.Manobras.FindAsync(id);
            _context.Manobras.Remove(manobra);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ManobraExists(int id)
        {
            return _context.Manobras.Any(e => e.Id == id);
        }
    }
}

ESTACIONAMENTO/Controllers/ManobristaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ESTACIONAMENTO.Dados;
using ESTACIONAMENTO.Models;

namespace ESTACIONAMENTO.Controllers
{
    public class ManobristaController : Controller
    {
        private readonly EstacionamentoContext _context;

        public ManobristaController(EstacionamentoContext context)
        {
            _context = context;
        }

        // GET: Manobrista
        public async Task<IActionResult> Index()
        {
            return View(await _context.Manobristas.ToListAsync());
        }

        // GET: Manobrista/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manobrista = await _context.Manobristas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manobrista == null)
            {
                return NotFound();
            }

            return View(manobrista);
        }

        // GET: Manobrista/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Manobrista/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,CPF,DataNascimento,Id")] Manobrista manobrista)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manobrista);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(manobrista);
        }

        // GET: Manobrista/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manobrista = await _context.Manobristas.FindAsync(id);
            if (manobrista == null)
            {
                return NotFound();
            }
            return View(manobrista);
        }

        // POST: Manobrista/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Nome,CPF,DataNascimento,Id")] Manobrista manobrista)
        {
            if (id != manobrista.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manobrista);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ManobristaExists(manobrista.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manobrista);
        }

        // GET: Manobrista/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manobrista = await _context.Manobristas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manobrista == null)
            {
                return NotFound();
            }

            return View(manobrista);
        }

        // POST: Manobrista/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manobrista = await _context.Manobristas.FindAsync(id);
            _context.Manobristas.Remove(manobrista);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ManobristaExists(int id)
        {
            return _context.Manobristas.Any(e => e.Id == id);
        }
    }
}

ESTACIONAMENTO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ESTACIONAMENTO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ESTACIONAMENTO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manobrista" asp-action="Index">Manobristas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carro" asp-action="Index">Carros</a>
                        </li>

                        @*Rotina substituida pelas IndexA e IndexF abaixo...*@
                        @*--------------------------------------------------*@
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Manobra" asp-action="Index">Manobras</a>
                            </li>*@

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manobra2" asp-action="IndexA">ManobrasAbertas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manobra2" asp-action="IndexF">ManobrasFechadas</a>
                        </li>


                        @*Rotina em desenvolvimento...*@
                        @*----------------------------*@
                        <li class="nav-item d-flex flex-column justify-content-center align-items-center text-dark">
                            <div class="dropdown">
                                <div class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Relatórios
                                    <span class="caret"></span>
                                </div>
                                <ul class="dropdown-menu bg-light" aria-labelledby="dropdownMenu1">
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Manobra2" asp-action="IndexR_E">Diversos</a>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Manobra2" asp-action="IndexR_S">Teste</a>
                                </ul>
                            </div>
                        </li>


                    </ul>

                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ESTACIONAMENTO - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ESTACIONAMENTO/Views/Shared/_SelecionarRel.cshtml
@model ESTACIONAMENTO.Models.Manobra2

@{
    ViewData["Title"] = "SelecionarRel";
}

<div>
    <form id="rel" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row">
            <div class="col-md-2">
                <div class="form-group">
                    <label class="control-label">Carro</label>
                    <select asp-for="CarroId" class="form-control" asp-items="ViewBag.Carros">
                        <option value="0">Selecione...</option>
                    </select>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label class="control-label">Manobrista</label>
                    <select asp-for="ManobristaId" class="form-control" asp-items="ViewBag.Manobristas">
                        <option value="0">Selecione...</option>
                    </select>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label class="control-label">Tipo Manobra</label>
                    <select asp-for="Classificacao" class="form-control" asp-items="ViewBag.Classificacoes">
                        <option value="0">Selecione...</option>
                    </select>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label class="control-label">Data De:</label>
                    <input type="date" asp-for="DataEntrada" id="inicio" name="inicio" class="form-control" style="background-color:gainsboro" />
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label class="control-label">Data Até:</label>
                    <input type="date" asp-for="DataEntrada" id="fim" name="fim" class="form-control" style="background-color:gainsboro" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Executar" class="btn btn-primary" onclick="" />
        </div>

    </form>

</div>